# Description:
#   Protocol buffer definitions used by AK
package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//src/tools/ak/package:__subpackages__"],
)

licenses(["notice"])

proto_library(
    name = "sync_proto",
    srcs = ["sync.proto"],
)
