alias(
    name = "toolchain_android_only",
    actual = "@bazel_tools//tools/jdk:current_java_toolchain",
    visibility = ["//visibility:public"],
)

alias(
    name = "toolchain",
    actual = "@bazel_tools//tools/jdk:toolchain",
    visibility = ["//visibility:public"],
)

alias(
    name = "current_java_runtime",
    actual = "@bazel_tools//tools/jdk:current_java_runtime",
    visibility = ["//visibility:public"],
)

alias(
    name = "current_java_toolchain",
    actual = "@bazel_tools//tools/jdk:current_java_toolchain",
    visibility = ["//visibility:public"],
)

alias(
    name = "jdk",
    actual = "@bazel_tools//tools/jdk:jdk",
    visibility = ["//visibility:public"],
)

alias(
    name = "current_host_java_runtime",
    actual = "@bazel_tools//tools/jdk:current_host_java_runtime",
    visibility = ["//visibility:public"],
)
