# Copyright 2018 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Bazel providers for Android rules."""

AndroidDeviceScriptFixtureInfo = provider(
    doc = "Provides information required to execute the device script fixture.",
    fields = dict(
        daemon = "Whether the fixture executes as a daemon.",
        fixture_script = "The fixture script artifact.",
        strict_exit = "Whether the a strict exit is required.",
        support_apps = "List of support app artifacts.",
    ),
)

AndroidHostServiceFixtureInfo = provider(
    doc = "Provides information required to execute the host service fixture.",
    fields = dict(
        daemon = "Whether the fixture executes as a daemon.",
        executable = "The executable artifact.",
        provides_test_args = "Whether the executable provides test args.",
        service_names = "List of services, by name, exposed by the fixture.",
        support_apps = "List of support app artifacts.",
    ),
)

SkylarkDeviceBrokerInfo = provider(
    doc = "Provides information about the device broker.",
    fields = dict(
        type = "Type of the device broker.",
    ),
)

AndroidDeviceBootActionInfo = provider(
    doc = "Provides outputs for the Boot phase of AndroidDevice",
    fields = dict(
        executable = "Executable Output Script",
        images = "Tarred images of the files in boot phase",
        metadata = "Proto information about the device",
        snapshot = "ram.bin file generated by Snapshot.",
    ),
)
