# Empty build file to satisfy gazelle for rules_go.

# TODO: remove these alias when ../..//BUILD remove them
alias(
    name = "androidsdk_sdk",
    actual = "@androidsdk//:sdk",
)

alias(
    name = "androidsdk_d8_jar_import",
    actual = "@androidsdk//:d8_jar_import",
)

alias(
    name = "androidsdk_dx_jar_import",
    actual = "@androidsdk//:dx_jar_import",
)

alias(
    name = "androidsdk_files",
    actual = "@androidsdk//:files",
)

alias(
    name = "androidsdk_has_android_sdk",
    actual = "@androidsdk//:has_android_sdk",
)
