package(default_applicable_licenses = ["//:license"])

licenses(["notice"])

exports_files([
    "EmptyAndroidManifest.xml",
    "HasTestRunnerAndroidManifest.xml",
    "NoChangeAndroidManifest.xml",
])
